### ISSUE TITLE
Author names should be in index

### ISSUE THREAD

**Issue by gladhorn** [lydiapintscher/20-years-of-KDE#13]
It would be lovely to have the chapters with authors in the index, to find someone's text by name.

**Comment by lydiapintscher** [comment]
I am not sure how to do that. Maybe @danimo can help?

**Comment by victorhck** [comment]
I also think that would be a great feature.
I don't know if this can be useful: http://tex.stackexchange.com/questions/47554/add-authors-name-automatically-while-building-toc
